-------------------------------------------------------------------------------
Test set: org.springframework.samples.petclinic.service.ClinicServiceTests
-------------------------------------------------------------------------------
Tests run: 11, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 6.434 s <<< FAILURE! - in org.springframework.samples.petclinic.service.ClinicServiceTests
shouldFindVets(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.111 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select vet0_.id as id1_10_, vet0_.first_name as first_na2_10_, vet0_.last_name as last_nam3_10_, vet0_.business_hours as business4_10_, vet0_.telephone as telephon5_10_ from vets vet0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindVets(ClinicServiceTests.java:188)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindVets(ClinicServiceTests.java:188)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: VETS in statement [select vet0_.id as id1_10_, vet0_.first_name as first_na2_10_, vet0_.last_name as last_nam3_10_, vet0_.business_hours as business4_10_, vet0_.telephone as telephon5_10_ from vets vet0_]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindVets(ClinicServiceTests.java:188)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: VETS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindVets(ClinicServiceTests.java:188)

shouldFindOwnersByLastName(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.067 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select distinct owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.last_name like ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindOwnersByLastName(ClinicServiceTests.java:81)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindOwnersByLastName(ClinicServiceTests.java:81)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS in statement [select distinct owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.last_name like ?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindOwnersByLastName(ClinicServiceTests.java:81)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindOwnersByLastName(ClinicServiceTests.java:81)

shouldAddNewVisitForPet(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.036 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select pet0_.id as id1_5_0_, pet0_.name as name2_5_0_, pet0_.birth_date as birth_da3_5_0_, pet0_.owner_id as owner_id4_5_0_, pet0_.type_id as type_id5_5_0_, owner1_.id as id1_4_1_, owner1_.first_name as first_na2_4_1_, owner1_.last_name as last_nam3_4_1_, owner1_.address as address4_4_1_, owner1_.city as city5_4_1_, owner1_.telephone as telephon6_4_1_, pettype2_.id as id1_8_2_, pettype2_.name as name2_8_2_, visits3_.pet_id as pet_id4_11_3_, visits3_.id as id1_11_3_, visits3_.id as id1_11_4_, visits3_.visit_date as visit_da2_11_4_, visits3_.description as descript3_11_4_, visits3_.pet_id as pet_id4_11_4_ from pets pet0_ left outer join owners owner1_ on pet0_.owner_id=owner1_.id left outer join types pettype2_ on pet0_.type_id=pettype2_.id left outer join visits visits3_ on pet0_.id=visits3_.pet_id where pet0_.id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldAddNewVisitForPet(ClinicServiceTests.java:200)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldAddNewVisitForPet(ClinicServiceTests.java:200)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: PETS in statement [select pet0_.id as id1_5_0_, pet0_.name as name2_5_0_, pet0_.birth_date as birth_da3_5_0_, pet0_.owner_id as owner_id4_5_0_, pet0_.type_id as type_id5_5_0_, owner1_.id as id1_4_1_, owner1_.first_name as first_na2_4_1_, owner1_.last_name as last_nam3_4_1_, owner1_.address as address4_4_1_, owner1_.city as city5_4_1_, owner1_.telephone as telephon6_4_1_, pettype2_.id as id1_8_2_, pettype2_.name as name2_8_2_, visits3_.pet_id as pet_id4_11_3_, visits3_.id as id1_11_3_, visits3_.id as id1_11_4_, visits3_.visit_date as visit_da2_11_4_, visits3_.description as descript3_11_4_, visits3_.pet_id as pet_id4_11_4_ from pets pet0_ left outer join owners owner1_ on pet0_.owner_id=owner1_.id left outer join types pettype2_ on pet0_.type_id=pettype2_.id left outer join visits visits3_ on pet0_.id=visits3_.pet_id where pet0_.id=?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldAddNewVisitForPet(ClinicServiceTests.java:200)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: PETS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldAddNewVisitForPet(ClinicServiceTests.java:200)

shouldUpdateOwner(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.063 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldUpdateOwner(ClinicServiceTests.java:119)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldUpdateOwner(ClinicServiceTests.java:119)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS in statement [select owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.id=?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldUpdateOwner(ClinicServiceTests.java:119)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldUpdateOwner(ClinicServiceTests.java:119)

shouldFindVisitsByPetId(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select visit0_.id as id1_11_, visit0_.visit_date as visit_da2_11_, visit0_.description as descript3_11_, visit0_.pet_id as pet_id4_11_ from visits visit0_ where visit0_.pet_id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindVisitsByPetId(ClinicServiceTests.java:215)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindVisitsByPetId(ClinicServiceTests.java:215)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: VISITS in statement [select visit0_.id as id1_11_, visit0_.visit_date as visit_da2_11_, visit0_.description as descript3_11_, visit0_.pet_id as pet_id4_11_ from visits visit0_ where visit0_.pet_id=?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindVisitsByPetId(ClinicServiceTests.java:215)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: VISITS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindVisitsByPetId(ClinicServiceTests.java:215)

shouldInsertPetIntoDatabaseAndGenerateId(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.015 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldInsertPetIntoDatabaseAndGenerateId(ClinicServiceTests.java:152)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldInsertPetIntoDatabaseAndGenerateId(ClinicServiceTests.java:152)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS in statement [select owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.id=?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldInsertPetIntoDatabaseAndGenerateId(ClinicServiceTests.java:152)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldInsertPetIntoDatabaseAndGenerateId(ClinicServiceTests.java:152)

shouldInsertOwner(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.02 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select distinct owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.last_name like ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldInsertOwner(ClinicServiceTests.java:100)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldInsertOwner(ClinicServiceTests.java:100)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS in statement [select distinct owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.last_name like ?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldInsertOwner(ClinicServiceTests.java:100)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldInsertOwner(ClinicServiceTests.java:100)

shouldFindSingleOwnerWithPet(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.235 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindSingleOwnerWithPet(ClinicServiceTests.java:90)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindSingleOwnerWithPet(ClinicServiceTests.java:90)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS in statement [select owner0_.id as id1_4_0_, pets1_.id as id1_5_1_, owner0_.first_name as first_na2_4_0_, owner0_.last_name as last_nam3_4_0_, owner0_.address as address4_4_0_, owner0_.city as city5_4_0_, owner0_.telephone as telephon6_4_0_, pets1_.name as name2_5_1_, pets1_.birth_date as birth_da3_5_1_, pets1_.owner_id as owner_id4_5_1_, pets1_.type_id as type_id5_5_1_, pets1_.owner_id as owner_id4_5_0__, pets1_.id as id1_5_0__ from owners owner0_ left outer join pets pets1_ on owner0_.id=pets1_.owner_id where owner0_.id=?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindSingleOwnerWithPet(ClinicServiceTests.java:90)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: OWNERS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindSingleOwnerWithPet(ClinicServiceTests.java:90)

shouldUpdatePetName(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.022 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select pet0_.id as id1_5_0_, pet0_.name as name2_5_0_, pet0_.birth_date as birth_da3_5_0_, pet0_.owner_id as owner_id4_5_0_, pet0_.type_id as type_id5_5_0_, owner1_.id as id1_4_1_, owner1_.first_name as first_na2_4_1_, owner1_.last_name as last_nam3_4_1_, owner1_.address as address4_4_1_, owner1_.city as city5_4_1_, owner1_.telephone as telephon6_4_1_, pettype2_.id as id1_8_2_, pettype2_.name as name2_8_2_, visits3_.pet_id as pet_id4_11_3_, visits3_.id as id1_11_3_, visits3_.id as id1_11_4_, visits3_.visit_date as visit_da2_11_4_, visits3_.description as descript3_11_4_, visits3_.pet_id as pet_id4_11_4_ from pets pet0_ left outer join owners owner1_ on pet0_.owner_id=owner1_.id left outer join types pettype2_ on pet0_.type_id=pettype2_.id left outer join visits visits3_ on pet0_.id=visits3_.pet_id where pet0_.id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldUpdatePetName(ClinicServiceTests.java:175)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldUpdatePetName(ClinicServiceTests.java:175)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: PETS in statement [select pet0_.id as id1_5_0_, pet0_.name as name2_5_0_, pet0_.birth_date as birth_da3_5_0_, pet0_.owner_id as owner_id4_5_0_, pet0_.type_id as type_id5_5_0_, owner1_.id as id1_4_1_, owner1_.first_name as first_na2_4_1_, owner1_.last_name as last_nam3_4_1_, owner1_.address as address4_4_1_, owner1_.city as city5_4_1_, owner1_.telephone as telephon6_4_1_, pettype2_.id as id1_8_2_, pettype2_.name as name2_8_2_, visits3_.pet_id as pet_id4_11_3_, visits3_.id as id1_11_3_, visits3_.id as id1_11_4_, visits3_.visit_date as visit_da2_11_4_, visits3_.description as descript3_11_4_, visits3_.pet_id as pet_id4_11_4_ from pets pet0_ left outer join owners owner1_ on pet0_.owner_id=owner1_.id left outer join types pettype2_ on pet0_.type_id=pettype2_.id left outer join visits visits3_ on pet0_.id=visits3_.pet_id where pet0_.id=?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldUpdatePetName(ClinicServiceTests.java:175)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: PETS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldUpdatePetName(ClinicServiceTests.java:175)

shouldFindAllPetTypes(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.015 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select pettype0_.id as id1_8_, pettype0_.name as name2_8_ from types pettype0_ order by pettype0_.name]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindAllPetTypes(ClinicServiceTests.java:141)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindAllPetTypes(ClinicServiceTests.java:141)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: TYPES in statement [select pettype0_.id as id1_8_, pettype0_.name as name2_8_ from types pettype0_ order by pettype0_.name]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindAllPetTypes(ClinicServiceTests.java:141)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: TYPES
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindAllPetTypes(ClinicServiceTests.java:141)

shouldFindPetWithCorrectId(org.springframework.samples.petclinic.service.ClinicServiceTests)  Time elapsed: 0.359 s  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select pet0_.id as id1_5_0_, pet0_.name as name2_5_0_, pet0_.birth_date as birth_da3_5_0_, pet0_.owner_id as owner_id4_5_0_, pet0_.type_id as type_id5_5_0_, owner1_.id as id1_4_1_, owner1_.first_name as first_na2_4_1_, owner1_.last_name as last_nam3_4_1_, owner1_.address as address4_4_1_, owner1_.city as city5_4_1_, owner1_.telephone as telephon6_4_1_, pettype2_.id as id1_8_2_, pettype2_.name as name2_8_2_, visits3_.pet_id as pet_id4_11_3_, visits3_.id as id1_11_3_, visits3_.id as id1_11_4_, visits3_.visit_date as visit_da2_11_4_, visits3_.description as descript3_11_4_, visits3_.pet_id as pet_id4_11_4_ from pets pet0_ left outer join owners owner1_ on pet0_.owner_id=owner1_.id left outer join types pettype2_ on pet0_.type_id=pettype2_.id left outer join visits visits3_ on pet0_.id=visits3_.pet_id where pet0_.id=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindPetWithCorrectId(ClinicServiceTests.java:133)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindPetWithCorrectId(ClinicServiceTests.java:133)
Caused by: java.sql.SQLSyntaxErrorException: usuario no tiene privilegios suficientes o objeto no encontrado: PETS in statement [select pet0_.id as id1_5_0_, pet0_.name as name2_5_0_, pet0_.birth_date as birth_da3_5_0_, pet0_.owner_id as owner_id4_5_0_, pet0_.type_id as type_id5_5_0_, owner1_.id as id1_4_1_, owner1_.first_name as first_na2_4_1_, owner1_.last_name as last_nam3_4_1_, owner1_.address as address4_4_1_, owner1_.city as city5_4_1_, owner1_.telephone as telephon6_4_1_, pettype2_.id as id1_8_2_, pettype2_.name as name2_8_2_, visits3_.pet_id as pet_id4_11_3_, visits3_.id as id1_11_3_, visits3_.id as id1_11_4_, visits3_.visit_date as visit_da2_11_4_, visits3_.description as descript3_11_4_, visits3_.pet_id as pet_id4_11_4_ from pets pet0_ left outer join owners owner1_ on pet0_.owner_id=owner1_.id left outer join types pettype2_ on pet0_.type_id=pettype2_.id left outer join visits visits3_ on pet0_.id=visits3_.pet_id where pet0_.id=?]
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindPetWithCorrectId(ClinicServiceTests.java:133)
Caused by: org.hsqldb.HsqlException: usuario no tiene privilegios suficientes o objeto no encontrado: PETS
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindPetWithCorrectId(ClinicServiceTests.java:133)

